name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install packages
      run: |
        sudo apt-get update
        sudo apt-get install csh clang-format parallel valgrind
	pip install virtualenv
    - name: setup
      run: cd tools; make test_env bats.done cpplint.done shellcheck.done sptk.done
    - name: make
      run: make -j 4
    - name: make format
      run: make format
    - name: make test
      run: make test
